version: "3"
services:
  testblog.demo.wbitt.com:
    image:  wordpress:latest
    labels:
      # If you enable traefik.enabled=true, then make 100% sure that the names you provide 
      # in host are actually pointing to the traefik server (web.witpass.co.uk).
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:testblog.demo.wbitt.com

    env_file:
      - testblog.env

    volumes:
      - /home/containers-data/testblog.demo.wbitt.com:/var/www/html

    networks:
      # This container uses the proxy-net / services-network
      - services-network

networks:
  # This 'services-network' network is created manually (on the server) by:
  # $ docker network create services-network 
  services-network:
    external: true

